name: MyPet-NPC
main: de.Keyle.MyPet.Npc.MyPetNpcPlugin
version: ${mypetnpc.version}
author: Keyle
website: ${project.url}
depend: [Citizens, MyPet]
commands:
  mypetnpcconfig:
    aliases: [mpnpcc]
    description: Configuration command for MyPet-NPC